### ISSUE TITLE
Add scientific name

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/rinse-checklist#3]
The scientific name of a species in RINSE is a compilation of the columns `genus` and `species`. To generate the taxonID, we need the full scientific name. However, when I paste `genus` and `species` into `scientificName`, some of the species are rather odd:

Brachyglottis x 'Sunshine'
Cotoneaster x 'Hybridus pendulus'
Triticosecale x
Hosta agg.
Medicago x varia
Larix x marschlinsii hyb.

Just to be sure that I'm generating `scientificName` correctly by pasting `genus` and `species` together. I don't think we should change the content, unless it is horribly wrong.

**Comment by peterdesmet** [comment]
1. I think you'll have to clean `species` first by removing things like:
    - `x`
    - `agg.`
    - `varia`
    - `hyb.`
    - `sp.`
    Considering those to be only genera.
2. Then you can combine names
3. Then you'll have to verify if don't have/created duplicates and remove those: hopefully they have the same distribution information.
4. And then generate taxonIDs.

Things like `'Sunshine'` are cultivars. I guess we want to keep them as cultivars (and thus generate a taxonID for them). GBIF won't be able to match them

**Comment by LienReyserhove** [comment]
Thank you for the input.

I'm going to clean the scientific names by removing:
- agg.
- sp.

I will leave all taxa containing an `x` untouched, but I will remove the `x` from `Triticosecale x`.

For `Larix x marschlinsii` :
@qgroom what do you mean with "in this case, the hyb. can be deleted"? There's another species like this, i.e. `Cuprocyparis x leylandii hyb.`. Can I drop the `hyb.` as well? 

With respect to the cultivars, I think we should leave them as they are. We only have 4 cultivars present in the dataset.

I still think we need to be carefull about removing information from `species`. I think all transformations that make the species match the backbone are good transformation in our case, given that we do not lose the original information. All other transformation should be avoided. That's why I'm not a fan of altering the cultivar information. OR we should double check with the authors.

**Comment by qgroom** [comment]
The 'hyb.' signifies that it is a hybrid, but as the 'x' also signifies that it is a hybrid then the hyb is redundant.

I'm fine with leaving the cultivar information.
Nevertheless, you might want to rename them to...
Brachyglottis 'Sunshine'
Cotoneaster 'Hybridus pendulus'

This is more normal for cultivars

**Comment by LienReyserhove** [comment]
This is an overview of the cleaning steps I undertook to generate the scientific names (a.o. = when more examples are available):

Note: in the original dataset, there was no column for information on infraspecific epithet. This information was combined with specific epithets in the column `species`. That's why the scientific names were included in the list of cleaned names here, i.e. I had to generate a new column for them.

OK?

scientificName (not clean) | genus (clean) | specific epithet (clean) | infraspecific epithet (new) | scientificName (clean)
--- | --- | --- | --- | ---
Brachyglottis x 'Sunshine' | Brachyglottis | 'Sunshine'| | Brachyglottis 'Sunshine'
Cotoneaster x 'Hybridus pendulus' | Cotoneaster | 'Hybridus pendulus' | | Cotoneaster 'Hybridus pendulus'
Fuchsia x 'Corallina' | Fuchsia | 'Corallina' | | Fuchsia 'Corallina'
Symphytum x 'Hidcote Blue' | Symphytum | 'Hidcote Blue' | | Symphytum 'Hidcote Blue'
Acmella agg. (a.o.) | Acmella | | | Acmella
Eucalyptus sp. (a.o.) | Eucalyptus | | | Eucalyptus
Scolelepis cf. bonnieri | Scolelepis | bonnieri | | Scolelepis bonnieri
Anchusa arvensis Orientalis (a.o.) | Anchusa | arvensis | orientalis | Anchusa arvensis orientalis
Lycium NA (a.o.) | Lycium | | | Lycium
Rosa Hollandica' | Rosa | 'Hollandica' | | Rosa 'Hollandica'
Sedum Herbstfreude' | Sedum | 'Herbstfreude' | | Sedum 'Herbstfreude'
Triticosecale x | Triticosecale | | | Triticosecale
Fusarium oxysporum f. | Fusarium | oxysporum || Fusarium oxysporum
AseroÙ rubra | Asero | rubra | | Asero rubra
Bluetongue n.a. (a.o.) | | | | Bluetongue


One I'm not sure of:
* Lipeurus maculosusIschnocera	--> should be Lipeurus maculosus ischnocera (could not find this one)?	
* Fusarium oxysporum f. --> taxonRank = form? (now indicated as species by parse function)

**Comment by peterdesmet** [comment]
Waw, some of these names are not well formed. 😄Most clean scientific names look ok. Some remarks:

- Anchusa arvensis orientalis: should be `Anchusa arvensis subsp. orientalis`. In fact, this is problematic for all species with an infraspecificEpithet. Will create separate issue for this.
- Scolelepis bonnieri: ideally, `cf.` should be kept in the scientificName and also indicated in http://rs.tdwg.org/dwc/terms/index.htm#identificationQualifier
- Fusarium oxysporum f.: I guess they mean "forms of Fusarium oxysporum", without indicating which forms. Is fine how it is parsed now.
- Bluetongue / Plum pox: are obviously vernacular names, and should be handled separately

**Comment by qgroom** [comment]
Ischnocera is a suborder of bird lice ([https://en.wikipedia.org/wiki/Ischnocera](https://en.wikipedia.org/wiki/Ischnocera)). Just _Lipeurus maculosus_ is correct. Things like this can only be sorted out manually.

**Comment by LienReyserhove** [comment]
I don't think there's a latin name for viruses such as Bluetongue or Plum pox, so I think `Bluetongue virus` and `Plum pox virus` are most fit for `scientificName`  (we need a scientificName for the generation of the taxonID)

**Comment by qgroom** [comment]
I've been considering viruses and bacteria out of scope.

**Comment by LienReyserhove** [comment]
I've updated the table above. I decided to use the information provided by the GBIF nameparser only for the mapping of `genus` and `infraspecificepithet`, to simplify things. `scientificName` was cleaned manually.
