### ISSUE TITLE
Phylum vs Division

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/rinse-checklist#4]
There's this column `phylum_devision`. As I am an ecologist and not an taxonomist, I kind of forgot what a division _exactly_ is (although I knew that it's a higher level of classification :sweat_smile: ). A quick search gave me this answer:

> Phylum vs Division Phylum and division are two taxonomic levels that are used in the biological classification of organisms. Both phylum and division occur below kingdom and above class. The main difference between phylum and division is that phylum is a classification level of the animal kingdom whereas division is the alternative classification level to the phylum in the kingdom Plantae and Fungi. Sometimes the term division is used as the lower classification level of the kingdom Protista and kingdom Monera. The kingdom Animalia comprises 36 phyla. The kingdom Plantae comprises 12 phyla, and the kingdom Fungi comprises 7 phyla.
 
So, can I put all devisions under the Darwin Core term `phylum`?

**Comment by LienReyserhove** [comment]
Anyway, I see that there's no DwC term for devision, so I will integrate all information from `phylum_devision` under the Dwc term `phylum`.

**Comment by qgroom** [comment]
Sure, I think they are equivalent.
