### ISSUE TITLE
nomenclatural code

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/rinse-checklist#6]
This field is obligatory, but not available in the raw data. As the raw dataset is a compilation of different datasets and phyla/kingdoms, I would be surprised that one single nomenclatural code could be used. Suggestions?

**Comment by peterdesmet** [comment]
Field is not obligatory (https://www.gbif.org/data-quality-requirements-checklists). I would either make assumption as @qgroom suggests or drop completely: this list is ‘t the strongest in writing (plant infraspecific) names correctly (#5), so we can’t state it is following a code.

**Comment by qgroom** [comment]
In that case leave it out. I can't think of anywhere else you need to state the code with the name. It can only be useful for dealing with homonyms and that is a very rare problem
